/**
 * api/cid.js — Vercel serverless function
 *
 * GET /api/cid?hash=0xabc...
 *
 * Resolves a contentHash → { cid, size } using the remediation manifest
 * for the 7k KB batch that was published on-chain with empty CIDs.
 *
 * The manifest (cid-manifest.json) is committed to the repo root after
 * running `npm run pin:remediate` in packages/generator.
 *
 * This endpoint is the fallback CID resolver used by:
 *   - api/query.js IPFS artifact fetch (when subgraph cid field is empty)
 *   - sdk-adapters fetchArtifact() (same)
 *   - demo/kb-detail.html artifact display
 *
 * Future KBs published via the two-phase pipeline have real CIDs on-chain
 * and do not need this endpoint.
 *
 * Response:
 *   200  { contentHash, cid, size, source: "manifest" }
 *   404  { error: "not found" }
 *   400  { error: "hash required" }
 */

import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

export const config = { maxDuration: 5 };

const __dirname = dirname(fileURLToPath(import.meta.url));

// Manifest location: packages/generator/staging/cid-manifest.json
// Generated by: npm run pin:remediate in packages/generator
// Must be committed to git so Vercel can read it at deploy time.
// .gitignore excludes individual KB JSONs from staging subdirs,
// but cid-manifest.json at staging root is NOT excluded — commit it.
let _manifest = null;
function getManifest() {
  if (_manifest) return _manifest;
  // api/__dirname → ../ → repo root → packages/generator/staging/cid-manifest.json
  const p = join(__dirname, "..", "packages", "generator", "staging", "cid-manifest.json");
  if (!existsSync(p)) {
    _manifest = {};
    return _manifest;
  }
  _manifest = JSON.parse(readFileSync(p, "utf8"));
  return _manifest;
}

export default function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");

  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "GET") return res.status(405).json({ error: "Method not allowed" });

  const { hash } = req.query;
  if (!hash) return res.status(400).json({ error: "hash query param required" });

  // Normalize: accept with or without 0x prefix, lowercase
  const normalized = (hash.startsWith("0x") ? hash : "0x" + hash).toLowerCase();

  const manifest = getManifest();

  // Try exact match first, then case-insensitive scan
  const entry = manifest[normalized]
    ?? manifest[normalized.toLowerCase()]
    ?? Object.entries(manifest).find(([k]) => k.toLowerCase() === normalized)?.[1];

  if (!entry) {
    return res.status(404).json({ error: "not found", hash: normalized });
  }

  return res.status(200).json({
    contentHash: normalized,
    cid:         entry.cid,
    size:        entry.size,
    source:      "manifest",
  });
}
